### ISSUE TITLE
where to start?

### ISSUE THREAD

**Issue by victuxbb** [OpenSocial/activitystreams#14]
Hi, in my current company(Schibsted) we want to implement events with the standard of Activity Stream 2.0 using Java.
I have a lot of doubts about this decision and maybe you can clarify me:

There is a java implementation for the Activity Stream 1.0?
There is a roadmap to have an stable version of the Activity Stream 2.0 in java? ( I would like to contribute ) 

Thanks! :)

**Comment by akuckartz** [comment]
@victuxbb This OpenSocial repository is dead.

But look here - AS2 is alive: https://github.com/jasnell/w3c-socialwg-activitystreams/

**Comment by victuxbb** [comment]
@akuckartz and what is the status of the project? It's an implementation in javascript? I don't see documentation...

Thanks!

**Comment by akuckartz** [comment]
@victuxbb The link I posted points to the _specification_ repository. The specification is still under development in the W3C Social Web WG..

A JavaScript implementation is available here: https://github.com/jasnell/activitystreams.js

**Comment by victuxbb** [comment]
@akuckartz Ok sorry for the confusion :)
I'm interested in the java implementation, I have found this one, I understand that is the alive project now?
https://github.com/jasnell/activitystreams

Thanks.

**Comment by jasnell** [comment]
@victuxbb ... i have a java implementation but it's fairly out of date. I'm not sure if I'm going to be able to get to it any time soon.
